### ISSUE TITLE
Java 9 does not support java.sql package outside of rt.jar

### ISSUE THREAD

**Issue by jericks** [jodygarnett/hatbox#1]
GeoScript Groovy can't connect to PostGIS when the new hatbox jar is on the classpath.

https://groups.google.com/forum/#!topic/geoscript/Ff2vqftzhqQ

The error we get is:

java.lang.SecurityException: Prohibited package name: java.sql
at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
at java.lang.ClassLoader.defineClass(ClassLoader.java:761)

The solution appears to be removing the hatbox java.sql package and upgrading the java compiler version to 1.6. The interfaces were only there to support java 1.5.

I am pretty sure that GeoTools will run into the same problem. I can send a pull request if you would like.

**Comment by jericks** [comment]
I created a pull request. 

https://github.com/jodygarnett/hatbox/pull/2

Thanks!
Jared

**Comment by jericks** [comment]
Hi Jody!

Would it be possible to merge the pull request and do another release?  When this hatbox jar is on the classpath, GeoScript Groovy can't connect to PostGIS.

Thanks!
Jared

**Comment by jericks** [comment]
This is not just a Java 9 issue.  It also occurs with Java 8.

**Comment by jcfandino** [comment]
@jericks Did you get any feedback on this issue?
This is a blocker for adopting this library.

**Comment by SJean-Marc** [comment]
The problem is still here for jdk 11, any tips to solve the issue please

**Comment by jericks** [comment]
I just tried emailing the GeoTools Developer Mailing list to see if we can get some help.

**Comment by jodygarnett** [comment]
Sorry I did not notice this was our official fork, I think we should transfer to GeoTools group!

**Comment by jericks** [comment]
Just to follow up, Jody merged my pull request and released a new version that fixed this problem.  The artifact can be found here:

https://repo.osgeo.org/service/rest/repository/browse/geotools-releases/net/sourceforge/hatbox/hatbox/1.0.b11/

Thank you Jody!
